version: '3'
services:
    app:
        container_name: python3-env
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./server:/usr/local/src
        privileged: true
        ports:
            - 8080:8080
        security_opt:
            apparmor:unconfined
        cap_add:
            SYS_PTRACE
        tty: true
    db:
        image: mysql:latest
        container_name: db-for-python3
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=dev
            - MYSQL_USER=$DB_ADMIN_USERNAME
            - MYSQL_PASSWORD=$DB_ADMIN_PASSWORD
            - TZ=Asia/Tokyo
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - "33306:3306"
        restart: always
        env_file:
            - ./.env
volumes:
    ./docker/db/data