version: '3'
services:
    app:
        container_name: python3-env
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        environment:
            - TZ=Asia/Tokyo
        volumes:
            - ./server:/usr/local/src
        ports:
            - 8080:8080
        tty: true
        networks:
            - python3_network
    db:
        image: mysql:latest
        container_name: db-for-python3
        environment:
            - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
            - MYSQL_DATABASE=dev
            - MYSQL_USER=$DB_ADMIN_USERNAME
            - MYSQL_PASSWORD=$DB_ADMIN_PASSWORD
            - TZ=Asia/Tokyo
        volumes:
            - ./docker/db/data:/var/lib/mysql
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/db/sql:/docker-entrypoint-initdb.d
        ports:
            - "33306:3306"
        restart: always
        env_file:
            - ./.env
        networks:
            - python3_network
networks:
    python3_network:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: "192.168.2.0/24"
              gateway: "192.168.2.1"